/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gitprac;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("lossl");
        return true;
    }
    //new comment 11
}
